Update action.yml

diff --git a/.github/actions/jfrog-upload/action.yml b/.github/actions/jfrog-upload/action.yml
--- a/.github/actions/jfrog-upload/action.yml
+++ b/.github/actions/jfrog-upload/action.yml
@@ -46,14 +46,21 @@ runs:
           --basic-auth-only=true \
           --interactive=false \
           --enc-password=false
-    - name: Prepare Properties
-      id: build-props
-      shell: bash
-      run: |
-        echo "Reading properties from ${{ inputs.properties-file }}..."
-        PROPS=$(jq -r 'to_entries | map("\(.key)=\(.value|tostring)") | join(";")' ${{ inputs.properties-file }})
-        echo "Generated Props: $PROPS"
-        echo "props=$PROPS" >> $GITHUB_OUTPUT
+        - name: Prepare Properties
+          id: build-props
+          shell: bash
+          run: |
+            FILE="${GITHUB_WORKSPACE}/${{ inputs.properties-file }}"
+            echo "Reading properties from $FILE..."
+            if [[ ! -f "$FILE" ]]; then
+              echo "❌ ERROR: Properties file not found: $FILE"
+              ls -R "${GITHUB_WORKSPACE}" || true
+              exit 1
+            fi
+            PROPS=$(jq -r 'to_entries | map("\(.key)=\(.value|tostring)") | join(";")' "$FILE")
+            echo "Generated Props: $PROPS"
+            echo "props=$PROPS" >> $GITHUB_OUTPUT
+
     
     - name: Upload file to Artifactory
       shell: bash
